name: Distribute Application

on:
  push:
    tags: [ "release*" ]

jobs:
  build:
    uses: sprintf/lemon-pi-dash/.github/workflows/base-build.yml@main

  create-docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: sync code
        uses: actions/checkout@v2
      - name: pull in previous artifact
        uses: actions/download-artifact@v2
        with:
          name: bootJar
          path: build/libs

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.MERINGUE_UPLOAD_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Configure Docker'
        run: gcloud auth configure-docker us.gcr.io

      - name: build docker image
        run: docker build -t us.gcr.io/meringue/dash:$GITHUB_SHA .

      - name: push docker image
        run: docker push us.gcr.io/meringue/dash:$GITHUB_SHA

